Mylogin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve



from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from account.mail_attachment import Mail_File_View,File_Path_View

from personal.views import (
    temp,
    home_proj,
    dashboard,
    

)


from account.views import (    
    register_view,
    login_view,
    logout_view,
    academy_add,
    research_add,
    prests_add,
    curpost_add,
    #teach_add,
    orient_add,
    
    
)

from catg_3.views import (	
    jrnl_add,
    
    pub_other_add,
    
    jrnl_paper_add,
    
    resch_sponsor_add,
    resch_cons_add,
    
    
    prj_add,
    
    resch_guide_add,
    
    fellow_award_add,
    
    
    lecture_paper_add,
    
    
    lecture_elearn_add,
   
    
)

urlpatterns = [	
       
	# path('admin/',include('admin_honeypot.urls',namespace='admin-honeypot')),
    path('juadmin/',admin.site.urls),

    path('mail',Mail_File_View,name='mail'),
    path('mailf',File_Path_View,name='mailf'),

    path('login', login_view, name="login"),
    path('account/', include('account.urls', namespace='account')),
    path('catg_3/', include('catg_3.urls', namespace='catg_3')),
    path('notify/', include('notify.urls', namespace='notify')),

    path('logout/', logout_view, name="logout"),  
    path('', register_view, name="register"),  
    path('academy-add', academy_add, name='academy-add'),
    path('jrnl-add', jrnl_add, name='jrnl-add'),
   
    path('pub-add', pub_other_add, name='pub-add'),
   
    path('jrnl-paper-add', jrnl_paper_add, name='jrnl-paper-add'),
 
    path('resch-sponsor-add', resch_sponsor_add, name='resch-sponsor-add'),
    path('resch-cons-add', resch_cons_add, name='resch-cons-add'),
   
    path('resch-guide-add', resch_guide_add, name='resch-guide-add'),
    
    path('fellow-award-add', fellow_award_add, name='fellow-award-add'),
    
    path('lecture-paper-add', lecture_paper_add, name='lecture-paper-add'),
    
    path('lecture-elearn-add', lecture_elearn_add, name='lecture-elearn-add'),
    
    path('prj-add', prj_add, name='prj-add'),
   
    
    path('research-add', research_add, name='research-add'),
    path('prests-add', prests_add, name='prests-add'),
    path('curpost-add', curpost_add, name='curpost-add'),
   
    path('orient-add', orient_add, name='orient-add'),
   
    path('temp/', temp, name='temp'),    
    path('home-proj/', home_proj, name='home-proj'),
    path('dashboard/', dashboard, name='dashboard'),
    
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),
        
    path('password_change2/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change2.html'), 
        name='password_change2'),
        
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),    
    
    path('password_change_done2', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done2.html'), 
        name='password_change_done2'),    
   
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/reset_password.html"),
         name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/reset.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/reset_password_complete.html"),
         name="password_reset_complete"),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    
     
     
]

    
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    


# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"    


account/urls.py
from django.urls import path
from . import views


from account.views import (
	account_view,
    edit_account_view,
    cas_view,
    academy_view,
    professional_view,
    teaching_view,    
    orient_view,
    cas_edit,
    cas_edit1,
    academy_edit1,    
    research_edit1,    
    prests_edit1,
    academy_delete,
    research_delete,
    prests_delete,
    curpost_edit1,
    curpost_delete,
    #teach_edit,
    #teach_edit1,
    #teach_delete,    
    orient_edit1,
    orient_delete,         
    self_view,
    api1_view,
    api2_view,
    ViewPDF,
    AboutView,
    NoticeView,
    InstructionView,
   
    
)

app_name = 'account'

urlpatterns = [

    path('about/', views.AboutView.as_view(), name='about'),
    path('notice/', views.NoticeView.as_view(), name='notice'),
    path('instruction/', views.InstructionView.as_view(), name='instruction'),
    
	path('<user_id>/', account_view, name="view"),
 	path('<user_id>/edit/', edit_account_view, name="edit"),
  	path('<user_id>/cas/', cas_view, name="cas"),
    path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),
    
    path('<user_id>/home/', self_view, name="home"),
    path('<user_id>/academy/', academy_view, name="academy"),
    path('<user_id>/professional/', professional_view, name="professional"),
    path('<user_id>/teaching/', teaching_view, name="teaching"),    
    path('<user_id>/orient/', orient_view, name="orient"),
    
    path('cas-edit/<str:pk>/', cas_edit, name="cas-edit"),
    path('cas-edit1/<str:pk>/', cas_edit1, name="cas-edit1"),
    
    path('academy-edit1/<str:pk>/', academy_edit1, name="academy-edit1"),
    path('academy-delete/<str:pk>/', academy_delete, name="academy-delete"),
   
    path('research-edit1/<str:pk>/', research_edit1, name="research-edit1"),
    path('research-delete/<str:pk>/', research_delete, name="research-delete"),

    path('prests-edit1/<str:pk>/', prests_edit1, name="prests-edit1"),
    path('prests-delete/<str:pk>/', prests_delete, name="prests-delete"),

    path('curpost-edit1/<str:pk>/', curpost_edit1, name="curpost-edit1"),
    path('curpost-delete/<str:pk>/', curpost_delete, name="curpost-delete"),

    path('orient-edit1/<str:pk>/', orient_edit1, name="orient-edit1"),
    path('orient-delete/<str:pk>/', orient_delete, name="orient-delete"),


    path('<user_id>/api-1/', api1_view, name="api-1"),
    path('<user_id>/api-2/', api2_view, name="api-2"),
       
    # path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),

]

catg_3/urls.py
from django.urls import path
from . import views

from catg_3.views import (
	jrnl_view,
	jrnl_edit,
    
 	jrnl_delete,
    pub_other_view,
	
	pub_edit,
	pub_delete,
    
	
	jrnl_paper_edit,
	jrnl_paper_delete,
    
	resch_proj_view,
 	
    
 	resch_edit,
    resch_cons_edit,
  	resch_delete,
    resch_cons_delete,
   	#prj_outcm_view,
    
    prj_edit,
    prj_delete,
    
    resch_guide_view,
    
    resch_guide_edit,
    resch_guide_delete,
    
    fellow_award_view,
    
    fellow_award_edit,
    fellow_award_delete,
        
    
    lecture_paper_edit,
    lecture_paper_delete,
    
    
    lecture_elearn_edit,
    lecture_elearn_delete,
    
    api_summary_view,
    LetterView,
    LetterPDF,
    cas_sts_view,
    
)


app_name = 'catg_3'

urlpatterns = [

    
    path('<user_id>/letter/', LetterView, name="letter"),
    path('<user_id>/endo-view/', LetterPDF.as_view(), name="endo-view"),
    
	path('<user_id>/jrnl-pub/', jrnl_view, name="jrnl-pub"),
	path('jrnl-edit/<str:pk>/', jrnl_edit, name="jrnl-edit"),
 	path('jrnl-delete/<str:pk>/', jrnl_delete, name="jrnl-delete"),
 	
    path('<user_id>/pub-other/', pub_other_view, name="pub-other"),
    
	path('pub-edit/<str:pk>/', pub_edit, name="pub-edit"),
	path('pub-delete/<str:pk>/', pub_delete, name="pub-delete"),

	path('jrnl-paper-edit/<str:pk>/', jrnl_paper_edit, name="jrnl-paper-edit"),
	path('jrnl-paper-delete/<str:pk>/', jrnl_paper_delete, name="jrnl-paper-delete"),

 	path('<user_id>/resch-view', resch_proj_view, name="resch-view"),
	path('resch-edit/<str:pk>/', resch_edit, name="resch-edit"),
    path('resch-cons-edit/<str:pk>/', resch_cons_edit, name="resch-cons-edit"),
	path('resch-delete/<str:pk>/', resch_delete, name="resch-delete"),
    path('resch-cons-delete/<str:pk>/', resch_cons_delete, name="resch-cons-delete"),

	#path('<user_id>/prj-outcm-view', prj_outcm_view, name="prj-outcm-view"),
	
	path('prj-edit/<str:pk>/', prj_edit, name="prj-edit"),
 	path('prj-delete/<str:pk>/', prj_delete, name="prj-delete"),
    
    path('<user_id>/resch-guide-view', resch_guide_view, name="resch-guide-view"),
	path('resch-guide-edit/<str:pk>/', resch_guide_edit, name="resch-guide-edit"),
	path('resch-guide-delete/<str:pk>/', resch_guide_delete, name="resch-guide-delete"),

    
    path('<user_id>/fellow-award-view', fellow_award_view, name="fellow-award-view"),
	path('fellow-award-edit/<str:pk>/', fellow_award_edit, name="fellow-award-edit"),
	path('fellow-award-delete/<str:pk>/', fellow_award_delete, name="fellow-award-delete"),

   
	path('lecture-paper-edit/<str:pk>/', lecture_paper_edit, name="lecture-paper-edit"),
	path('lecture-paper-delete/<str:pk>/', lecture_paper_delete, name="lecture-paper-delete"),


	path('lecture-elearn-edit/<str:pk>/', lecture_elearn_edit, name="lecture-elearn-edit"),
	path('lecture-elearn-delete/<str:pk>/', lecture_elearn_delete, name="lecture-elearn-delete"),
    
    path('<user_id>/api-summary-view', api_summary_view, name="api-summary-view"),
    path('<user_id>/cas-sts-view', cas_sts_view, name="cas-sts-view"),    

     
    

]

catg_3/templates/catg_3/book.html
<div >

    <form method="POST" action="book">
        {% csrf_token %}
        {{formset.management_form}}

        {% for form in formset%}
        {{form}}
        <hr>
        {% endfor %}
        <br/>
        <div >
            <button type="submit" class="btn btn-danger btn-lg">Submit</button>
        </div>

    </form>

</div>

catg_3/templates/catg_3/jrnl_delete.html
{% extends 'base_v2.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item.title_pub}}"?</p>

			<form action="{% url 'catg_3:jrnl-delete' item.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'catg_3:jrnl-pub' user_id=request.user.id %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

catg_3/templates/catg_3/lecture_paper_delete.html
{% extends 'base_v2.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item.title_lecture}}"?</p>
			
			<form action="{% url 'catg_3:lecture-paper-delete' item.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'catg_3:fellow-award-view' user_id=request.user.id %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

catg_3/templates/catg_3/resch_proj.html
{% extends 'base_v2.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<style>
     html {
        font-family: verdana;
        font-size: 10pt;        
      }
      
      table {
        border-collapse: collapse;
        overflow-x: scroll !important;
	    white-space: nowrap;       
        display: block;
      }
     tr{
         width:1200px;
     } 
     td,
     th {        
        height: 15px;
        width:200px;
        border: dashed 1px lightblue;
        }
     td{       
       font-size:20px;       
     }   
     .form-number{
        text-align: center; 
        width: 60pt;        
     }

     input[type=number]::-webkit-inner-spin-button, 
     input[type=number]::-webkit-outer-spin-button { 
           -webkit-appearance: none; 
           margin: 0; 
     }
     .card {
      margin: 0 auto; /* Added */
      float: none; /* Added */
      margin-bottom: 10px; /* Added */
      }
     
</style>



<form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}

 <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 95%;">
          
    <div class="card-body">
        <h2 class="card-title" style="font-weight:bold;">CATEGORY III : Research and Academic Contribution
			<a href="{% url 'account:home' user_id=request.user.id %}" class="previous" style="text-decoration:none;float:right;"><i class="fa fa-window-close" style="font-size:36px"></i></a>
		</h2>
        <h3 class="card-title" style="font-weight:bold;">III-C :  Research Projects :</h3>
        <h3 class="card-title" style="color:blue;">(i)  Sponsored Project
		  {% if user.is_applicant %}
				<a href="{% url 'resch-sponsor-add' %}" class="w3-button w3-circle w3-teal" style="text-decoration:none;">+</a>
				<small style="color:Tomato;font-weight:bolder;">Add</small>
				<br>
			
          {% endif %}
		
		</h3>
		
    <br> 

    <table class="table">
        
            <tr>
                
                <th VALIGN=TOP>Sl.No.</th>
                <th VALIGN=TOP style="text-align: center;">Area of the Applicant</th>
                <th VALIGN=TOP style="width: 10%;">Title of the Project</th>
                <th VALIGN=TOP style="text-align: center;">Name of the Funding <br> Agency</th>
                <th VALIGN=TOP style="text-align: center;">Duration <br> (no.of years)</th>
                <th VALIGN=TOP style="text-align: center;">Grant Sanctioned<br>(in Lakhs)</th>
                <th VALIGN=TOP style="width: 30%;">Upload Grant<br>Letter link </th>           
               
                <th VALIGN=TOP>Self Appraisal Score</th>
				{% if admin %}
					<th VALIGN=TOP>Verified API Score</th>
				{% endif %}
				
                {% if user.is_applicant %}				
					          <th  VALIGN=TOP colspan="2">&nbsp&nbsp&nbsp&nbspActions</th>
				{% endif %}           
                
            </tr>
       
			<script>
				var spon_score=0;
			</script>
			
      {% for item in res|dictsort:"id" %}
	  
           
              <tr>
                <td style="display:none;">{{form.email}}</td>             
                
                <td>{{ forloop.counter }}</td>
               
                <td>{{item.get_faculty_app_display|default_if_none:"Blank"}}</td>               
                <td><textarea rows="3" cols="40" wrap="hard" readonly>{{item.proj_title|default_if_none:"Blank"}}</textarea></td>
                <td><textarea rows="3" cols="30" wrap="hard" readonly>{{item.fund_agnc|default_if_none:"Blank"}}</textarea></td>
                <td style="text-align:center;">{{item.no_yrs}}</td>
                <td style="text-align:center;">{{item.prj_amt}}</td>        
                
                
                {% if item.prj_url %}
                    <td><a class="btn btn-secondary btn-lg" href='{{ item.prj_url }}' target=_blank>View</a></td>
                {% else %}
                    <td>None</td>
                {% endif %}
                
                            
                <td style="text-align:center;">{{item.self_api_score|default_if_none:"Blank"}}</td>
				
					<script>
						var spon_score = spon_score + parseFloat({{item.self_api_score}});						
					</script>
				{% if admin %}
					<td style="text-align:center;">{{item.veri_api_score|default_if_none:"Blank"}}</td>
				{% endif %}
          
                 {% if user.is_applicant %}
                      <td><a style="font-weight:bolder;" name="edit-btn" class="text-information" href="{% url 'catg_3:resch-edit' pk=item.id %}">Edit</a></td>
                      <td><a style="font-weight:bolder;" class="text-warning" href="{% url 'catg_3:resch-delete' pk=item.id %}">Delete</a></td>				
                 {% endif %} 
                      

            </tr>
			
         
		  
       {% endfor %}

          {% if not res %}
          <tr>
            <td colspan="9" style="line-height: 10px;background-color:powderblue;text-align:center;" >No data available in table</td>
          </tr>
          {% endif %}
          

    </table>
	 
        <label id="spon_score" style="font-size:20px;font-weight:bold;"></label>

  </div>
  <hr>
  <!--IIIC (ii)  Consultancy Project -->

  <div class="card-body">    
    
    <h3 class="card-title" style="color:blue;">(ii)  Consultancy Project
        
		{% if user.is_applicant %} 
				<a href="{% url 'resch-cons-add' %}" class="w3-button w3-circle w3-teal" style="text-decoration:none;">+</a>
				<small style="color:Tomato;font-weight:bolder;">Add</small>
		{% endif %}
		
	</h3>	
      
<br> 

<table class="table">
    
        <tr>
            
            <th VALIGN=TOP>Sl.No.</th>
            <th VALIGN=TOP style="text-align: center;">Area of the Applicant</th>
            <th VALIGN=TOP style="width: 10%;">Title of the Project</th>
            <th VALIGN=TOP style="text-align: center;">Name of the Funding <br> Agency</th>
            <th VALIGN=TOP style="text-align: center;">Duration <br> (in months)</th>
            <th VALIGN=TOP style="text-align: center;">Amount Mobilized<br>(in lakhs)</th>
            <th VALIGN=TOP style="width: 30%;">Upload Grant<br>Letter link</th>           
           
            <th VALIGN=TOP>Self Appraisal Score</th>
			{% if admin %}
				<th VALIGN=TOP>Verified API Score</th>
			{% endif %} 
            {% if user.is_applicant %}				
                <th  VALIGN=TOP colspan="2">&nbsp&nbsp&nbsp&nbspActions</th>
            {% endif %}           
            
        </tr>
	
       
			<script>
				var cons_score=0;
			</script>
			
  {% for item in cons %}
        {% if item.proj_title and item.proj_tag == "cons" %}
          <tr>
            <td style="display:none;">{{form.email}}</td>             
            <td style="display:none;">{{prj_tag}}</td>            
			<td>{{ forloop.counter }}</td>			
            <td>{{item.get_faculty_app_display|default_if_none:"Blank"}}</td>               
            <td><textarea rows="3" cols="40" wrap="hard" readonly>{{item.proj_title|default_if_none:"Blank"}}</textarea></td>
            <td><textarea rows="3" cols="40" wrap="hard" readonly>{{item.fund_agnc|default_if_none:"Blank"}}</textarea></td>
            <td style="text-align:center;">{{item.no_yrs}}</td>
            <td style="text-align:center;">{{item.prj_amt}}</td>        
            
            
            {% if item.prj_url %}
                <td><a class="btn btn-secondary btn-lg" href='{{ item.prj_url }}' target=_blank>View</a></td>
            {% else %}
                <td>None</td>
            {% endif %}
            
                        
            <td style="text-align:center;">{{item.self_api_score|default_if_none:"Blank"}}</td>
			
				<script>
						var cons_score = cons_score + parseFloat({{item.self_api_score}});						
				</script>
				
			{% if admin %}	
				<td style="text-align:center;">{{item.veri_api_score|default_if_none:"Blank"}}</td>
			{% endif %}
      
             {% if user.is_applicant %}
                  <td><a style="font-weight:bolder;" name="edit-btn" class="text-information" href="{% url 'catg_3:resch-cons-edit' pk=item.id %}">Edit</a></td>
                  <td><a style="font-weight:bolder;" class="text-warning" href="{% url 'catg_3:resch-cons-delete' pk=item.id %}">Delete</a></td>				
             {% endif %} 
                  

        </tr>
      {% endif %}
   {% endfor %}

    {% if not cons %}
			<tr>
				<td colspan="9" style="line-height: 10px;background-color:powderblue;text-align:center;" >No data available in table</td>
			</tr>
		{% endif %}
	   

</table>

 <label id="cons_score" style="font-size:20px;font-weight:bold;"></label>

</div>
<hr>
<!--IIIC (iii)  Projects Outcome/Output -->

<div class="card-body">    
    
	<h3 class="card-title" style="color:blue;">(iii)  Projects Outcome/Output
	
		{% if user.is_applicant %} 
				<a href="{% url 'prj-add' %}" class="w3-button w3-circle w3-teal" style="text-decoration:none;">+</a>
				<small style="color:Tomato;font-weight:bolder;">Add</small>
		{% endif %}
  
	</h3>      

<br>
<table class="table">
  
      <tr>
          
          <th VALIGN=TOP>Sl.No.</th>
          <th VALIGN=TOP style="text-align: center;">Area of the Applicant</th>
          <th VALIGN=TOP style="width: 10%;">Type</th>
          <th VALIGN=TOP style="text-align: center;">Title</th>
          <th VALIGN=TOP style="text-align: center;">Level</th>
          <th VALIGN=TOP style="text-align: center;">Document No./<br>Patent No/<br>Other reference no</th>
          <th VALIGN=TOP style="width: 30%;">Status (if patent only)</th>
          <th VALIGN=TOP style="width: 30%;">Upload document link</th>           
         
          <th VALIGN=TOP>Self Appraisal Score</th>
		  {% if admin %}
			<th VALIGN=TOP>Verified API Score</th>
		  {% endif %} 
          {% if user.is_applicant %}				
              <th  VALIGN=TOP colspan="2">&nbsp&nbsp&nbsp&nbspActions</th>
          {% endif %}           
          
      </tr>
 

			<script>
				var proj_score=0;
			</script>
			
{% for item in prj %}
      {% if item.proj_title %}
        <tr>
          <td style="display:none;">{{form.email}}</td>            
          <td>{{ forloop.counter }}</td>		  
          <td>{{item.get_faculty_app_display|default_if_none:"Blank"}}</td>               
          <td>{{item.get_prj_type_display|default_if_none:"Blank"}}</td>
          <td><textarea rows="3" cols="40" wrap="hard" readonly>{{item.proj_title|default_if_none:"Blank"}}</textarea></td>
          <td>{{item.get_prj_lvl_display|default_if_none:"Blank"}}</td>
          <td style="text-align:center;">{{item.ref_no}}</td>
		  {% if item.ptnt_sts %}
			<td>{{item.get_ptnt_sts_display}}</td>
          {% else %}
			<td style="text-align: left;">N/A</td>
		  {% endif %}
          {% if item.prj_url %}
              <td><a class="btn btn-secondary btn-lg" href='{{ item.prj_url }}' target=_blank>View</a></td>
          {% else %}
              <td>None</td>
          {% endif %}
          
                      
          <td style="text-align:center;">{{item.self_api_score|default_if_none:"Blank"}}</td>
		  
				<script>
						var proj_score = proj_score + parseFloat({{item.self_api_score}});						
				</script>
			{% if admin %}	
				<td style="text-align:center;">{{item.veri_api_score|default_if_none:"Blank"}}</td>
			{% endif %}
    
           {% if user.is_applicant %}
                <td><a style="font-weight:bolder;" name="edit-btn" class="text-information" href="{% url 'catg_3:prj-edit' pk=item.id %}">Edit</a></td>
                <td><a style="font-weight:bolder;" class="text-warning" href="{% url 'catg_3:prj-delete' pk=item.id %}">Delete</a></td>				
           {% endif %} 
                

      </tr>
    {% endif %}
 {% endfor %}
    {% if not prj %}
    <tr>
      <td colspan="10" style="line-height: 10px;background-color:powderblue;text-align:center;" >No data available in table</td>
    </tr>
    {% endif %}


</table>

 <label id="proj_score" style="font-size:20px;font-weight:bold;"></label>


			<div class="row" >			
				<a href="{% url 'catg_3:pub-other' user_id=pk_var %}" style="margin-left:12px;width:5%;height:50%;font-weight:bold;margin-right:20px;font-size:2rem;" class="btn btn-primary btn-lg">&laquo;</a>
				<a href="{% url 'catg_3:resch-guide-view' user_id=pk_var %}" style="float:right;width:5%;font-weight:bold;font-size:2rem;" class="btn btn-success btn-lg">&raquo;</a>
			</div>

	

</div>

</div>
</form>

<script type="text/javascript">

	document.getElementById("spon_score").innerHTML = "API Total [III-C(i)] : " + (spon_score.toFixed(2));
	document.getElementById("cons_score").innerHTML = "API Total [III-C(ii)]): " + (cons_score.toFixed(2));
	document.getElementById("proj_score").innerHTML = "API Total [III-C(iii)]: " + (proj_score.toFixed(2));
	
	
</script>

{% endblock content %}
    