Mylogin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve



from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from account.mail_attachment import Mail_File_View,File_Path_View

from personal.views import (
    temp,
    home_proj,
    dashboard,
    

)


from account.views import (    
    register_view,
    login_view,
    logout_view,
    academy_add,
    research_add,
    prests_add,
    curpost_add,
    #teach_add,
    orient_add,
    
    
)

from catg_3.views import (	
    jrnl_add,
    
    pub_other_add,
    
    jrnl_paper_add,
    
    resch_sponsor_add,
    resch_cons_add,
    
    
    prj_add,
    
    resch_guide_add,
    
    fellow_award_add,
    
    
    lecture_paper_add,
    
    
    lecture_elearn_add,
   
    
)

urlpatterns = [	
       
	# path('admin/',include('admin_honeypot.urls',namespace='admin-honeypot')),
    path('juadmin/',admin.site.urls),

    path('mail',Mail_File_View,name='mail'),
    path('mailf',File_Path_View,name='mailf'),

    path('login', login_view, name="login"),
    path('account/', include('account.urls', namespace='account')),
    path('catg_3/', include('catg_3.urls', namespace='catg_3')),
    path('notify/', include('notify.urls', namespace='notify')),

    path('logout/', logout_view, name="logout"),  
    path('', register_view, name="register"),  
    path('academy-add', academy_add, name='academy-add'),
    path('jrnl-add', jrnl_add, name='jrnl-add'),
   
    path('pub-add', pub_other_add, name='pub-add'),
   
    path('jrnl-paper-add', jrnl_paper_add, name='jrnl-paper-add'),
 
    path('resch-sponsor-add', resch_sponsor_add, name='resch-sponsor-add'),
    path('resch-cons-add', resch_cons_add, name='resch-cons-add'),
   
    path('resch-guide-add', resch_guide_add, name='resch-guide-add'),
    
    path('fellow-award-add', fellow_award_add, name='fellow-award-add'),
    
    path('lecture-paper-add', lecture_paper_add, name='lecture-paper-add'),
    
    path('lecture-elearn-add', lecture_elearn_add, name='lecture-elearn-add'),
    
    path('prj-add', prj_add, name='prj-add'),
   
    
    path('research-add', research_add, name='research-add'),
    path('prests-add', prests_add, name='prests-add'),
    path('curpost-add', curpost_add, name='curpost-add'),
   
    path('orient-add', orient_add, name='orient-add'),
   
    path('temp/', temp, name='temp'),    
    path('home-proj/', home_proj, name='home-proj'),
    path('dashboard/', dashboard, name='dashboard'),
    
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),
        
    path('password_change2/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change2.html'), 
        name='password_change2'),
        
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),    
    
    path('password_change_done2', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done2.html'), 
        name='password_change_done2'),    
   
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/reset_password.html"),
         name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/reset.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/reset_password_complete.html"),
         name="password_reset_complete"),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    
     
     
]

    
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    


# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"    


account/urls.py
from django.urls import path
from . import views


from account.views import (
	account_view,
    edit_account_view,
    cas_view,
    academy_view,
    professional_view,
    teaching_view,    
    orient_view,
    cas_edit,
    cas_edit1,
    academy_edit1,    
    research_edit1,    
    prests_edit1,
    academy_delete,
    research_delete,
    prests_delete,
    curpost_edit1,
    curpost_delete,
    #teach_edit,
    #teach_edit1,
    #teach_delete,    
    orient_edit1,
    orient_delete,         
    self_view,
    api1_view,
    api2_view,
    ViewPDF,
    AboutView,
    NoticeView,
    InstructionView,
   
    
)

app_name = 'account'

urlpatterns = [

    path('about/', views.AboutView.as_view(), name='about'),
    path('notice/', views.NoticeView.as_view(), name='notice'),
    path('instruction/', views.InstructionView.as_view(), name='instruction'),
    
	path('<user_id>/', account_view, name="view"),
 	path('<user_id>/edit/', edit_account_view, name="edit"),
  	path('<user_id>/cas/', cas_view, name="cas"),
    path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),
    
    path('<user_id>/home/', self_view, name="home"),
    path('<user_id>/academy/', academy_view, name="academy"),
    path('<user_id>/professional/', professional_view, name="professional"),
    path('<user_id>/teaching/', teaching_view, name="teaching"),    
    path('<user_id>/orient/', orient_view, name="orient"),
    
    path('cas-edit/<str:pk>/', cas_edit, name="cas-edit"),
    path('cas-edit1/<str:pk>/', cas_edit1, name="cas-edit1"),
    
    path('academy-edit1/<str:pk>/', academy_edit1, name="academy-edit1"),
    path('academy-delete/<str:pk>/', academy_delete, name="academy-delete"),
   
    path('research-edit1/<str:pk>/', research_edit1, name="research-edit1"),
    path('research-delete/<str:pk>/', research_delete, name="research-delete"),

    path('prests-edit1/<str:pk>/', prests_edit1, name="prests-edit1"),
    path('prests-delete/<str:pk>/', prests_delete, name="prests-delete"),

    path('curpost-edit1/<str:pk>/', curpost_edit1, name="curpost-edit1"),
    path('curpost-delete/<str:pk>/', curpost_delete, name="curpost-delete"),

    path('orient-edit1/<str:pk>/', orient_edit1, name="orient-edit1"),
    path('orient-delete/<str:pk>/', orient_delete, name="orient-delete"),


    path('<user_id>/api-1/', api1_view, name="api-1"),
    path('<user_id>/api-2/', api2_view, name="api-2"),
       
    # path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),

]

catg_3/urls.py
from django.urls import path
from . import views

from catg_3.views import (
	jrnl_view,
	jrnl_edit,
    
 	jrnl_delete,
    pub_other_view,
	
	pub_edit,
	pub_delete,
    
	
	jrnl_paper_edit,
	jrnl_paper_delete,
    
	resch_proj_view,
 	
    
 	resch_edit,
    resch_cons_edit,
  	resch_delete,
    resch_cons_delete,
   	#prj_outcm_view,
    
    prj_edit,
    prj_delete,
    
    resch_guide_view,
    
    resch_guide_edit,
    resch_guide_delete,
    
    fellow_award_view,
    
    fellow_award_edit,
    fellow_award_delete,
        
    
    lecture_paper_edit,
    lecture_paper_delete,
    
    
    lecture_elearn_edit,
    lecture_elearn_delete,
    
    api_summary_view,
    LetterView,
    LetterPDF,
    cas_sts_view,
    
)


app_name = 'catg_3'

urlpatterns = [

    
    path('<user_id>/letter/', LetterView, name="letter"),
    path('<user_id>/endo-view/', LetterPDF.as_view(), name="endo-view"),
    
	path('<user_id>/jrnl-pub/', jrnl_view, name="jrnl-pub"),
	path('jrnl-edit/<str:pk>/', jrnl_edit, name="jrnl-edit"),
 	path('jrnl-delete/<str:pk>/', jrnl_delete, name="jrnl-delete"),
 	
    path('<user_id>/pub-other/', pub_other_view, name="pub-other"),
    
	path('pub-edit/<str:pk>/', pub_edit, name="pub-edit"),
	path('pub-delete/<str:pk>/', pub_delete, name="pub-delete"),

	path('jrnl-paper-edit/<str:pk>/', jrnl_paper_edit, name="jrnl-paper-edit"),
	path('jrnl-paper-delete/<str:pk>/', jrnl_paper_delete, name="jrnl-paper-delete"),

 	path('<user_id>/resch-view', resch_proj_view, name="resch-view"),
	path('resch-edit/<str:pk>/', resch_edit, name="resch-edit"),
    path('resch-cons-edit/<str:pk>/', resch_cons_edit, name="resch-cons-edit"),
	path('resch-delete/<str:pk>/', resch_delete, name="resch-delete"),
    path('resch-cons-delete/<str:pk>/', resch_cons_delete, name="resch-cons-delete"),

	#path('<user_id>/prj-outcm-view', prj_outcm_view, name="prj-outcm-view"),
	
	path('prj-edit/<str:pk>/', prj_edit, name="prj-edit"),
 	path('prj-delete/<str:pk>/', prj_delete, name="prj-delete"),
    
    path('<user_id>/resch-guide-view', resch_guide_view, name="resch-guide-view"),
	path('resch-guide-edit/<str:pk>/', resch_guide_edit, name="resch-guide-edit"),
	path('resch-guide-delete/<str:pk>/', resch_guide_delete, name="resch-guide-delete"),

    
    path('<user_id>/fellow-award-view', fellow_award_view, name="fellow-award-view"),
	path('fellow-award-edit/<str:pk>/', fellow_award_edit, name="fellow-award-edit"),
	path('fellow-award-delete/<str:pk>/', fellow_award_delete, name="fellow-award-delete"),

   
	path('lecture-paper-edit/<str:pk>/', lecture_paper_edit, name="lecture-paper-edit"),
	path('lecture-paper-delete/<str:pk>/', lecture_paper_delete, name="lecture-paper-delete"),


	path('lecture-elearn-edit/<str:pk>/', lecture_elearn_edit, name="lecture-elearn-edit"),
	path('lecture-elearn-delete/<str:pk>/', lecture_elearn_delete, name="lecture-elearn-delete"),
    
    path('<user_id>/api-summary-view', api_summary_view, name="api-summary-view"),
    path('<user_id>/cas-sts-view', cas_sts_view, name="cas-sts-view"),    

     
    

]

notify/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime
from ckeditor.fields import RichTextField

# Create your models here.
class Message(models.Model):
    sender          = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_messages')
    receiver        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_messages')
    content         = RichTextField()
    timestamp       = models.DateTimeField(auto_now_add=True)
    read            = models.BooleanField(default=False)
    modified_date   = models.DateTimeField(auto_now=True)
    receiver_name   = models.TextField()
    email           = models.EmailField()
    feedback        = models.TextField()
   
    
    def __str__(self):
        return f"{self.sender} -> {self.receiver}: {self.content}"

templates/password_reset/password_change.html
{% extends 'base_v2.html' %}
{% load static %}

{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;    
    max-width: 330px;
    padding: 15px;
    margin-left: 300px;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>

<div class="container" style="height:1240px;">
<form  id="id_password_change_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required="true">
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>  
</form>
</div>

{% endblock content%}

templates/password_reset/password_change2.html
{% extends 'main2.html' %}
{% load static %}

{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;    
    max-width: 330px;
    padding: 15px;
    margin-left: 300px;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>

<div class="container" style="margin-left:400px;margin-top:100px;height:1240px;">
<form  id="id_password_change_form" action="" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Change your initial password</h1>
    <input name="old_password" class="form-control" placeholder="Initial password" type="password" id="id_old_password" required="true">
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">
	
    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>  
  <a href="{% url 'register' %}" style="float:right;height:45px;width:60%;font-weight:bold;font-size:1.5rem;" class="btn btn-success btn-lg">&laquo;&nbsp&nbsp&nbspBack</a>
		
</form>
</div>

<script type="text/javascript">

 
</script>
{% endblock content%}

templates/password_reset/password_change_done.html

{% extends 'main2.html' %}
{% load static %}

{% block content %}

<div class="container" style="margin-top:200px;height:1240px;">


    <div class="d-flex flex-column" style="margin-left:350px;">
		<h2>
        <p class="m-auto" style="font-weight:bold;">
		  {% if request.user.is_first_login %}
		    Your password has been set. You may go ahead and <br><br>
				<a style="margin-left:40px;" href="{% url 'account:home' user_id=request.user.id %}">Login in 'CAS Portal'</a>
				&nbsp now or &nbsp<a href="{% url 'logout' %}">later</a>
				
		  {% else %} 
			Your password has been set. You may go ahead and <br><br>
				<a style="margin-left:40px;" href="{% url 'login' %}">Login in 'CAS Portal'</a>
				&nbsp now or &nbsp<a href="{% url 'logout' %}">later</a>			
		  {% endif %}
			
		
		</p>
		</h2>
    </div>


	
</div>

{% endblock %}

templates/password_reset/password_change_done2.html

{% extends 'main2.html' %}
{% load static %}

{% block content %}

<div class="container" style="margin-top:200px;height:1240px;">


    <div class="d-flex flex-column" style="margin-left:350px;">
		<h2>
        <p class="m-auto" style="font-weight:bold;">
		  {% if request.user.is_first_login %}
		     You have successfully registered in CAS portal <br>
			 &nbsp&nbsp&nbsp <span style="color:tomato;">initial password for first login send by email</span> <br><br>
				<a style="margin-left:40px;" href="{% url 'login' %}">Login in 'CAS Portal'</a>
				&nbsp now or &nbsp<a href="{% url 'logout' %}">later</a>
		  {% endif %}
			
		
		</p>
		</h2>
    </div>


	
</div>

{% endblock %}

templates/password_reset/password_first_setting.html
{% extends 'main2.html' %}
{% load static %}

{% block content %}

<div class="container" style="margin-top:200px;height:1240px;">


    <div class="d-flex flex-column" style="margin-left:350px;">
		<h2>
        <p class="m-auto" style="font-weight:bold;">
		  {% if request.user.is_first_login %}
		     You have successfully registered in CAS portal <br>
			 &nbsp&nbsp&nbsp <span style="color:tomato;">initial password send to your email account</span> <br><br>
				<a style="margin-left:40px;" href="{% url 'password_change2' %}">Login in 'CAS Portal'</a>
				&nbsp now or &nbsp<a href="{% url 'logout' %}">later</a>
		  			
		  {% endif %}
			
		
		</p>
		</h2>
    </div>


	
</div>

{% endblock %}

templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'home' %}">Return to home page</a></p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Open-Chat Team
{% endautoescape %}

templates/password_reset/password_reset_form.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


<form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
    <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true" >
  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" >Send reset email</button>  
</form>



{% endblock %}

templates/password_reset/reset.html
{% extends 'main2.html' %}

{% block content %}

<style>
    input[type='text'],
    input[type='email'],
    input[type='password'] {
        min-width: 24rem;
        width: 100%;
        padding: 1.2rem 1.5rem;
        border-radius: 0.5rem;
        border: 2px solid var(--color-light);
        transition: all 0.3s ease-in-out;
        background-color: var(--color-bg);
    }

    input[type='text']:focus,
    input[type='email']:focus,
    input[type='password']:focus,
    input[type='text']:active,
    input[type='email']:active,
    input[type='password']:active {
        outline: none;
        border: 2px solid var(--color-main);
    }
</style>


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3 style="font-weight:bold;">Enter new password</h3>

            <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input style="font-weight:bold;font-size:25px;color:white;" class="btn btn-secondary btn-block btn-lg" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

templates/password_reset/reset_password.html
{% extends 'main2.html' %}

{% block content %}

<style>
    input[type='text'],
    input[type='email'],
    input[type='password'] {
        min-width: 24rem;
        width: 100%;
        padding: 1.2rem 1.5rem;
        border-radius: 0.5rem;
        border: 2px solid var(--color-light);
        transition: all 0.3s ease-in-out;
        background-color: var(--color-bg);
    }

    input[type='text']:focus,
    input[type='email']:focus,
    input[type='password']:focus,
    input[type='text']:active,
    input[type='email']:active,
    input[type='password']:active {
        outline: none;
        border: 2px solid var(--color-main);
    }
</style>

<body>
<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3 style="font-weight:bold;">Password reset</h3>

            <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new
                one.</p>

            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input style="font-weight:bold;font-size:25px;color:white;" class="btn btn-secondary btn-block btn-lg" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
</body>
{% endblock content %}

templates/password_reset/reset_password_complete.html
{% extends 'main2.html' %}

{% block content %}


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3 style="font-weight:bold;">Password reset complete</h3>

            <p>Your password has been set. You may go ahead and log in now.</p>
            <br>
            <a style="font-weight:bold;font-size:25px;color:white;" class="btn btn-secondary btn-block btn-lg" href="{% url 'register' %}">Login</a>
        </div>
    </div>
</main>

{% endblock content %}

templates/password_reset/reset_password_sent.html
{% extends 'main2.html' %}

{% block content %}


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3 style="font-weight:bold;">Password reset sent</h3>

            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you
                entered. You should receive them shortly.</p>
            <br>
            <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check
                your spam folder.</p>
        </div>
    </div>
</main>

{% endblock content %}