Mylogin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve



from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from account.mail_attachment import Mail_File_View,File_Path_View

from personal.views import (
    temp,
    home_proj,
    dashboard,
    

)


from account.views import (    
    register_view,
    login_view,
    logout_view,
    academy_add,
    research_add,
    prests_add,
    curpost_add,
    #teach_add,
    orient_add,
    
    
)

from catg_3.views import (	
    jrnl_add,
    
    pub_other_add,
    
    jrnl_paper_add,
    
    resch_sponsor_add,
    resch_cons_add,
    
    
    prj_add,
    
    resch_guide_add,
    
    fellow_award_add,
    
    
    lecture_paper_add,
    
    
    lecture_elearn_add,
   
    
)

urlpatterns = [	
       
	# path('admin/',include('admin_honeypot.urls',namespace='admin-honeypot')),
    path('juadmin/',admin.site.urls),

    path('mail',Mail_File_View,name='mail'),
    path('mailf',File_Path_View,name='mailf'),

    path('login', login_view, name="login"),
    path('account/', include('account.urls', namespace='account')),
    path('catg_3/', include('catg_3.urls', namespace='catg_3')),
    path('notify/', include('notify.urls', namespace='notify')),

    path('logout/', logout_view, name="logout"),  
    path('', register_view, name="register"),  
    path('academy-add', academy_add, name='academy-add'),
    path('jrnl-add', jrnl_add, name='jrnl-add'),
   
    path('pub-add', pub_other_add, name='pub-add'),
   
    path('jrnl-paper-add', jrnl_paper_add, name='jrnl-paper-add'),
 
    path('resch-sponsor-add', resch_sponsor_add, name='resch-sponsor-add'),
    path('resch-cons-add', resch_cons_add, name='resch-cons-add'),
   
    path('resch-guide-add', resch_guide_add, name='resch-guide-add'),
    
    path('fellow-award-add', fellow_award_add, name='fellow-award-add'),
    
    path('lecture-paper-add', lecture_paper_add, name='lecture-paper-add'),
    
    path('lecture-elearn-add', lecture_elearn_add, name='lecture-elearn-add'),
    
    path('prj-add', prj_add, name='prj-add'),
   
    
    path('research-add', research_add, name='research-add'),
    path('prests-add', prests_add, name='prests-add'),
    path('curpost-add', curpost_add, name='curpost-add'),
   
    path('orient-add', orient_add, name='orient-add'),
   
    path('temp/', temp, name='temp'),    
    path('home-proj/', home_proj, name='home-proj'),
    path('dashboard/', dashboard, name='dashboard'),
    
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),
        
    path('password_change2/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change2.html'), 
        name='password_change2'),
        
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),    
    
    path('password_change_done2', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done2.html'), 
        name='password_change_done2'),    
   
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/reset_password.html"),
         name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/reset.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/reset_password_complete.html"),
         name="password_reset_complete"),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    
     
     
]

    
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    


# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"    


account/urls.py
from django.urls import path
from . import views


from account.views import (
	account_view,
    edit_account_view,
    cas_view,
    academy_view,
    professional_view,
    teaching_view,    
    orient_view,
    cas_edit,
    cas_edit1,
    academy_edit1,    
    research_edit1,    
    prests_edit1,
    academy_delete,
    research_delete,
    prests_delete,
    curpost_edit1,
    curpost_delete,
    #teach_edit,
    #teach_edit1,
    #teach_delete,    
    orient_edit1,
    orient_delete,         
    self_view,
    api1_view,
    api2_view,
    ViewPDF,
    AboutView,
    NoticeView,
    InstructionView,
   
    
)

app_name = 'account'

urlpatterns = [

    path('about/', views.AboutView.as_view(), name='about'),
    path('notice/', views.NoticeView.as_view(), name='notice'),
    path('instruction/', views.InstructionView.as_view(), name='instruction'),
    
	path('<user_id>/', account_view, name="view"),
 	path('<user_id>/edit/', edit_account_view, name="edit"),
  	path('<user_id>/cas/', cas_view, name="cas"),
    path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),
    
    path('<user_id>/home/', self_view, name="home"),
    path('<user_id>/academy/', academy_view, name="academy"),
    path('<user_id>/professional/', professional_view, name="professional"),
    path('<user_id>/teaching/', teaching_view, name="teaching"),    
    path('<user_id>/orient/', orient_view, name="orient"),
    
    path('cas-edit/<str:pk>/', cas_edit, name="cas-edit"),
    path('cas-edit1/<str:pk>/', cas_edit1, name="cas-edit1"),
    
    path('academy-edit1/<str:pk>/', academy_edit1, name="academy-edit1"),
    path('academy-delete/<str:pk>/', academy_delete, name="academy-delete"),
   
    path('research-edit1/<str:pk>/', research_edit1, name="research-edit1"),
    path('research-delete/<str:pk>/', research_delete, name="research-delete"),

    path('prests-edit1/<str:pk>/', prests_edit1, name="prests-edit1"),
    path('prests-delete/<str:pk>/', prests_delete, name="prests-delete"),

    path('curpost-edit1/<str:pk>/', curpost_edit1, name="curpost-edit1"),
    path('curpost-delete/<str:pk>/', curpost_delete, name="curpost-delete"),

    path('orient-edit1/<str:pk>/', orient_edit1, name="orient-edit1"),
    path('orient-delete/<str:pk>/', orient_delete, name="orient-delete"),


    path('<user_id>/api-1/', api1_view, name="api-1"),
    path('<user_id>/api-2/', api2_view, name="api-2"),
       
    # path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),

]

catg_3/urls.py
from django.urls import path
from . import views

from catg_3.views import (
	jrnl_view,
	jrnl_edit,
    
 	jrnl_delete,
    pub_other_view,
	
	pub_edit,
	pub_delete,
    
	
	jrnl_paper_edit,
	jrnl_paper_delete,
    
	resch_proj_view,
 	
    
 	resch_edit,
    resch_cons_edit,
  	resch_delete,
    resch_cons_delete,
   	#prj_outcm_view,
    
    prj_edit,
    prj_delete,
    
    resch_guide_view,
    
    resch_guide_edit,
    resch_guide_delete,
    
    fellow_award_view,
    
    fellow_award_edit,
    fellow_award_delete,
        
    
    lecture_paper_edit,
    lecture_paper_delete,
    
    
    lecture_elearn_edit,
    lecture_elearn_delete,
    
    api_summary_view,
    LetterView,
    LetterPDF,
    cas_sts_view,
    
)


app_name = 'catg_3'

urlpatterns = [

    
    path('<user_id>/letter/', LetterView, name="letter"),
    path('<user_id>/endo-view/', LetterPDF.as_view(), name="endo-view"),
    
	path('<user_id>/jrnl-pub/', jrnl_view, name="jrnl-pub"),
	path('jrnl-edit/<str:pk>/', jrnl_edit, name="jrnl-edit"),
 	path('jrnl-delete/<str:pk>/', jrnl_delete, name="jrnl-delete"),
 	
    path('<user_id>/pub-other/', pub_other_view, name="pub-other"),
    
	path('pub-edit/<str:pk>/', pub_edit, name="pub-edit"),
	path('pub-delete/<str:pk>/', pub_delete, name="pub-delete"),

	path('jrnl-paper-edit/<str:pk>/', jrnl_paper_edit, name="jrnl-paper-edit"),
	path('jrnl-paper-delete/<str:pk>/', jrnl_paper_delete, name="jrnl-paper-delete"),

 	path('<user_id>/resch-view', resch_proj_view, name="resch-view"),
	path('resch-edit/<str:pk>/', resch_edit, name="resch-edit"),
    path('resch-cons-edit/<str:pk>/', resch_cons_edit, name="resch-cons-edit"),
	path('resch-delete/<str:pk>/', resch_delete, name="resch-delete"),
    path('resch-cons-delete/<str:pk>/', resch_cons_delete, name="resch-cons-delete"),

	#path('<user_id>/prj-outcm-view', prj_outcm_view, name="prj-outcm-view"),
	
	path('prj-edit/<str:pk>/', prj_edit, name="prj-edit"),
 	path('prj-delete/<str:pk>/', prj_delete, name="prj-delete"),
    
    path('<user_id>/resch-guide-view', resch_guide_view, name="resch-guide-view"),
	path('resch-guide-edit/<str:pk>/', resch_guide_edit, name="resch-guide-edit"),
	path('resch-guide-delete/<str:pk>/', resch_guide_delete, name="resch-guide-delete"),

    
    path('<user_id>/fellow-award-view', fellow_award_view, name="fellow-award-view"),
	path('fellow-award-edit/<str:pk>/', fellow_award_edit, name="fellow-award-edit"),
	path('fellow-award-delete/<str:pk>/', fellow_award_delete, name="fellow-award-delete"),

   
	path('lecture-paper-edit/<str:pk>/', lecture_paper_edit, name="lecture-paper-edit"),
	path('lecture-paper-delete/<str:pk>/', lecture_paper_delete, name="lecture-paper-delete"),


	path('lecture-elearn-edit/<str:pk>/', lecture_elearn_edit, name="lecture-elearn-edit"),
	path('lecture-elearn-delete/<str:pk>/', lecture_elearn_delete, name="lecture-elearn-delete"),
    
    path('<user_id>/api-summary-view', api_summary_view, name="api-summary-view"),
    path('<user_id>/cas-sts-view', cas_sts_view, name="cas-sts-view"),    

     
    

]

templates/snippets/base_css.html
<style type="text/css">
	head{
		font-family: "Segoe UI";
		font-weight: 380;
	}
	footer{
		font-family: "Segoe UI";
		font-weight: 380;
	}
	body{
		background-color: #f2f2f2;
		font-family: "Segoe UI";
		font-weight: 380;
	}

	:root{
		--main-background-color: #f2f2f2;
		--dark-background-color: #a2a2a2;
		--secondary-text-color: #808080;
		--light-primary-text-color: #0080ff;
	}
	
	


</style>

templates/snippets/base_js.html
<script type="text/javascript">
	
</script>

templates/snippets/footer.html
{% load static %}
<style type="text/css">
	.footer{
		min-height: 100px;
		background-color:grey;
	}
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
	<p class="m-auto">S. Chakraborty | 2022</p>
</div>
<!-- End Footer -->

templates/snippets/sidebar.html
{% load static %}
<head>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <style>


	.dropdown {
	  display: block;
	  position: relative;
	 
	}
	.dropdown-menu{
	  display: none;
	  float:right;
	  background-color:  #ffffe6;
	  position: absolute;
	  width: 110%;
	  margin:300px;
	  margin-top:580px;;
	  overflow: auto;
	  box-shadow: 0px 10px 10px 0px rgba(0,0,0,0.4);
	}
	
	.dropdown-menu a {
	  display: block;
	  color: #000000;
	  padding: 2px;
	  text-decoration: none;
	}
	.arrow{
	  color:black;
	  
	  margin-left: 10px;
	}
	a:hover{
	  text-decoration:none;
	}

	.menu-sample {
		  list-style: none;
		  padding: 5px;
	}

	.menu-item-sample:hover {
		  background-color: red;
	}

	.menu-item-sample.active {
		  background-color: green;
	}
	.w3-sidebar{
		background-color:#1d4666;
		color:white;
	}

	div{
		margin:0;
		padding:0;
	}

  </style>

</head>

<div id="main">

  {% if request.user.is_authenticated %}

<nav class="w3-sidebar w3-collapse" style="z-index:1;width:300px;overflow: visible;margin-top:52px;box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s3">
      <i class="fa fa-user-circle" style="font-size:48px;"></i>
    </div>
    {% if user.is_admin %}
    <div class="w3-col s4 w3-bar w3-text-white" style="padding-top:10px;">
      <span1 style="font-size:medium;">Welcome, <br> <strong>{{ request.user.username }}</strong></span1><br>
	  
        
    {% else %}
                    
                    <div class="w3-col s8 w3-bar w3-text-white" style="padding-top:10px;">
                        <span1 style="font-size:medium;">Welcome, <br> <strong>{{ request.user.username }}</strong></span1><br>    
                      {% endif %}        
                    </div>
           
 
 {% endif %}        
 
    
  </div>
  <hr>
  <div class="w3-container">
    <h5 style="color:#BCC747">Quick Links</h5>
  </div>
  <div class="w3-bar-block " style="font-size:medium;">
		
		<ul class="menu-sample">
        
        <li class="menu-item-sample"><a href="{% url 'account:home' user_id=request.user.id %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa-dashboard fa-fw"></i>  Dashboard</a></li>
        <li class="menu-item-sample"><a id="id_gen" href="{% url 'account:cas' user_id=request.user.id %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa fa-vcard fa-fw"></i>  General Information</a></li>
        
		<li class="menu-item-sample"><a href="{% url 'account:academy' user_id=request.user.id %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa fa-graduation-cap fa-fw"></i>  Academic Qualifications</a></li>
       
		<li class="menu-item-sample"><a href="{% url 'account:professional' user_id=request.user.id %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa fa-briefcase fa-fw"></i>  Professional Experience</a></li>
        <li class="menu-item-sample"><a href="{% url 'account:teaching' user_id=request.user.id %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa fa-book fa-fw"></i>  Teaching Experience</a></li>
        <li class="menu-item-sample"><a href="{% url 'account:orient' user_id=request.user.id %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa-bell fa-fw"></i> Orientation / Refresher Courses</a></li>
        
        </ul>
		
	 <button class="w3-button w3-block w3-left-align w3-hover-red" onclick="myAccFunc1()"><i class="fa fa-tasks fa-fw "></i> API Categories <i class="fa fa-caret-down fa-fw" style="font-size:15px;margin-left:7px;"></i>
  </button>
  <div id="demoAcc1" class="w3-hide w3-white w3-card">
    <a href="{% url 'account:api-1' user_id=request.user.id %}" class="w3-bar-item w3-button w3-hover-red">API Criteria I</a>
    <a href="{% url 'account:api-2' user_id=request.user.id %}" class="w3-bar-item w3-button w3-hover-red">API Criteria II</a>
    
    <div class=" dropdown">
      
      <button type="button" class="w3-button w3-block w3-left-align w3-hover-red" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        API Criteria III  <span class="arrow"><i class="fa fa-caret-right"></i></span>
      </button>
      <div class="dropdown-menu" >
        <a href="#" onclick="showLoaderOnClick('{% url 'catg_3:jrnl-pub' user_id=request.user.id %}')" class="w3-bar-item w3-button w3-hover-red"> A. Journal Publication</a>
		<!--<a href="{% url 'catg_3:jrnl-pub' user_id=request.user.id %}" class="w3-bar-item w3-button w3-hover-red"> A. Journal Publication</a>-->
        <a href="{% url 'catg_3:pub-other' user_id=request.user.id %}" class="w3-bar-item w3-button w3-hover-red"> B. Publications other than Journal Articles</a>
        <a href="{% url 'catg_3:resch-view' user_id=request.user.id %}" class="w3-bar-item w3-button w3-hover-red"> C. Research Projects</a>
        <a href="{% url 'catg_3:resch-guide-view' user_id=request.user.id %}" class="w3-bar-item w3-button w3-hover-red"> D. Research Guidance</a>
        <a href="{% url 'catg_3:fellow-award-view' user_id=request.user.id %}" class="w3-bar-item w3-button w3-hover-red"> E. Fellowships/Awards/Invited Lecture</a>
      </div>  
	  </div>

    
  
  </div>
  <a href="{% url 'catg_3:api-summary-view' user_id=request.user.id %}"  class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa-calculator fa-fw"></i>  API Score Summary</a>
  <hr>
	  <!--<a href="#" onclick="showLoaderOnClick('{% url 'account:pdf_view' user_id=request.user.id %}')" target="_blank" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa-file-pdf-o fa-fw"></i>  Generate PDF</a>-->
	  <a href="{% url 'account:pdf_view' user_id=request.user.id %}" target="_blank" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa-file-pdf-o fa-fw"></i>  Generate PDF</a>

    <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa-power-off fa-fw"></i>  Logout</a>
    <a href="{% url 'password_change' %}" class="w3-bar-item w3-button w3-padding w3-hover-red"><i class="fa fa-cog fa-fw"></i>  Change Password</a><br><br>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}


function myAccFunc1() {
  var x = document.getElementById("demoAcc1");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-grey";
  } else { 
    x.className = x.className.replace(" w3-show", "");
    x.previousElementSibling.className = 
    x.previousElementSibling.className.replace(" w3-grey", "");
  }
}

function myAccFunc2() {
  var x = document.getElementById("demoAcc2");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-blue";
  } else { 
    x.className = x.className.replace(" w3-show", "");
    x.previousElementSibling.className = 
    x.previousElementSibling.className.replace(" w3-blue", "");
  }
}

$(document).ready(function() {
    $('.menu-item-sample li').click(function() {
        $('li.active').removeClass("active");
        $(this).addClass("active");
    });
});

function showLoaderOnClick(url) {
				  showLoader();
				  window.location=url;
	}

function showLoader(){
	 $('body').append('<div style="" id="loadingDiv"><div class="loader">Please wait page is Loading...</div></div>');
}

		

</script>

templates/snippets/sidebar_black.html
{% load static %}



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<style>
.sidebar{
	
	padding:0;
	margin-left:0;
}
.elements{
	width:320px;
	margin:0;
	height:60px;
	padding-top:10px;
	color:white;
	text-decoration:none;
	font-size: 25px;
	border-bottom:2px solid grey;
	border-radius: 15px 50px 30px 5px;
	}

.api{
	color:white;
	font-size: 20px;
}



</style>





<div class="sidebar">
					
		
		  
			<a  class="elements" href="{% url 'account:home' user_id=request.user.id %}"> Dashboard</a>
			<a  class="elements" href="{% url 'account:cas' user_id=request.user.id %}"> General Information</a>
			<a  class="elements" href="{% url 'account:academy' user_id=request.user.id %}"> Academic Qualifications</a>
			<a  class="elements" href="#"> Professional Experience</a>
			<a  class="elements" href="#"> Teaching Experience</a>
			<a  class="elements" href="#" style="height:90px;"> Orientation/Refresher Courses</a>
			
			
			<!--
			<div class="dropdown">
				<a class="elements" data-toggle="dropdown"> API Categories
				</a>
		    -->		

				<div class="menu">
					<li class="item" id="mn1" style="list-style:none;">
						<a class="btn" href="#mn1" style="text-align:left;font-size:25px;">API Categories</a>
						<div class="submenu">
							<a style="text-align:left;font-size:25px;color:white;" href="#">Criterion I</a>
							{% comment %}

							{% if not user.is_applicant %}                
								{% if user_var %}
								<a style="text-align:left;font-size:25px;color:white;" href="{% url 'account:api-1' user_id=pk_var %}">Criterion I</a>
								{% endif %}
							{% else %}
								<a style="text-align:left;font-size:25px;color:white;" href="{% url 'account:api-1' user_id=request.user.id %}">Criterion I</a>
							{% endif %}

							{% endcomment %}


							<a style="text-align:left;font-size:25px;color:white;" href="#">Criterion II</a>
							<a style="text-align:left;font-size:25px;color:white;" href="#">Criterion III</a>
						</div>
					</li>
				</div>		







				<!--
				{% include 'snippets/bs_accordian.html' %}
				
				<ul class="dropdown-menu">
					<li href="#">Criterion I</li>
					<li href="#">Criterion II</li>
					
					<li href="#">Criterion III</li>
					
					<ul>
						<li href="#">A. Journal Publication</li>
						<li href="#">B. Publications other than Journal Articles</li>
						<li href="#">C. Research Projects</li>
						<li href="#">D. Research Guidance</li>
						<li href="#">E. Fellowships/Awards/Invited Lecture</li>
					</ul>
				
				</ul>
			</div>
				--> 
			

			<a  class="elements" href="{% url 'password_change' %}"> Change Password</a>
			<a  class="elements" href="{% url 'logout' %}"> Logout</a>

		
					
</div>
