Mylogin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve



from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from account.mail_attachment import Mail_File_View,File_Path_View

from personal.views import (
    temp,
    home_proj,
    dashboard,
    

)


from account.views import (    
    register_view,
    login_view,
    logout_view,
    academy_add,
    research_add,
    prests_add,
    curpost_add,
    #teach_add,
    orient_add,
    
    
)

from catg_3.views import (	
    jrnl_add,
    
    pub_other_add,
    
    jrnl_paper_add,
    
    resch_sponsor_add,
    resch_cons_add,
    
    
    prj_add,
    
    resch_guide_add,
    
    fellow_award_add,
    
    
    lecture_paper_add,
    
    
    lecture_elearn_add,
   
    
)

urlpatterns = [	
       
	# path('admin/',include('admin_honeypot.urls',namespace='admin-honeypot')),
    path('juadmin/',admin.site.urls),

    path('mail',Mail_File_View,name='mail'),
    path('mailf',File_Path_View,name='mailf'),

    path('login', login_view, name="login"),
    path('account/', include('account.urls', namespace='account')),
    path('catg_3/', include('catg_3.urls', namespace='catg_3')),
    path('notify/', include('notify.urls', namespace='notify')),

    path('logout/', logout_view, name="logout"),  
    path('', register_view, name="register"),  
    path('academy-add', academy_add, name='academy-add'),
    path('jrnl-add', jrnl_add, name='jrnl-add'),
   
    path('pub-add', pub_other_add, name='pub-add'),
   
    path('jrnl-paper-add', jrnl_paper_add, name='jrnl-paper-add'),
 
    path('resch-sponsor-add', resch_sponsor_add, name='resch-sponsor-add'),
    path('resch-cons-add', resch_cons_add, name='resch-cons-add'),
   
    path('resch-guide-add', resch_guide_add, name='resch-guide-add'),
    
    path('fellow-award-add', fellow_award_add, name='fellow-award-add'),
    
    path('lecture-paper-add', lecture_paper_add, name='lecture-paper-add'),
    
    path('lecture-elearn-add', lecture_elearn_add, name='lecture-elearn-add'),
    
    path('prj-add', prj_add, name='prj-add'),
   
    
    path('research-add', research_add, name='research-add'),
    path('prests-add', prests_add, name='prests-add'),
    path('curpost-add', curpost_add, name='curpost-add'),
   
    path('orient-add', orient_add, name='orient-add'),
   
    path('temp/', temp, name='temp'),    
    path('home-proj/', home_proj, name='home-proj'),
    path('dashboard/', dashboard, name='dashboard'),
    
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),
        
    path('password_change2/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change2.html'), 
        name='password_change2'),
        
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),    
    
    path('password_change_done2', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done2.html'), 
        name='password_change_done2'),    
   
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/reset_password.html"),
         name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/reset.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/reset_password_complete.html"),
         name="password_reset_complete"),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    
     
     
]

    
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    


# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"    


account/urls.py
from django.urls import path
from . import views


from account.views import (
	account_view,
    edit_account_view,
    cas_view,
    academy_view,
    professional_view,
    teaching_view,    
    orient_view,
    cas_edit,
    cas_edit1,
    academy_edit1,    
    research_edit1,    
    prests_edit1,
    academy_delete,
    research_delete,
    prests_delete,
    curpost_edit1,
    curpost_delete,
    #teach_edit,
    #teach_edit1,
    #teach_delete,    
    orient_edit1,
    orient_delete,         
    self_view,
    api1_view,
    api2_view,
    ViewPDF,
    AboutView,
    NoticeView,
    InstructionView,
   
    
)

app_name = 'account'

urlpatterns = [

    path('about/', views.AboutView.as_view(), name='about'),
    path('notice/', views.NoticeView.as_view(), name='notice'),
    path('instruction/', views.InstructionView.as_view(), name='instruction'),
    
	path('<user_id>/', account_view, name="view"),
 	path('<user_id>/edit/', edit_account_view, name="edit"),
  	path('<user_id>/cas/', cas_view, name="cas"),
    path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),
    
    path('<user_id>/home/', self_view, name="home"),
    path('<user_id>/academy/', academy_view, name="academy"),
    path('<user_id>/professional/', professional_view, name="professional"),
    path('<user_id>/teaching/', teaching_view, name="teaching"),    
    path('<user_id>/orient/', orient_view, name="orient"),
    
    path('cas-edit/<str:pk>/', cas_edit, name="cas-edit"),
    path('cas-edit1/<str:pk>/', cas_edit1, name="cas-edit1"),
    
    path('academy-edit1/<str:pk>/', academy_edit1, name="academy-edit1"),
    path('academy-delete/<str:pk>/', academy_delete, name="academy-delete"),
   
    path('research-edit1/<str:pk>/', research_edit1, name="research-edit1"),
    path('research-delete/<str:pk>/', research_delete, name="research-delete"),

    path('prests-edit1/<str:pk>/', prests_edit1, name="prests-edit1"),
    path('prests-delete/<str:pk>/', prests_delete, name="prests-delete"),

    path('curpost-edit1/<str:pk>/', curpost_edit1, name="curpost-edit1"),
    path('curpost-delete/<str:pk>/', curpost_delete, name="curpost-delete"),

    path('orient-edit1/<str:pk>/', orient_edit1, name="orient-edit1"),
    path('orient-delete/<str:pk>/', orient_delete, name="orient-delete"),


    path('<user_id>/api-1/', api1_view, name="api-1"),
    path('<user_id>/api-2/', api2_view, name="api-2"),
       
    # path('<user_id>/pdf_view/', ViewPDF.as_view(), name="pdf_view"),

]

catg_3/urls.py
from django.urls import path
from . import views

from catg_3.views import (
	jrnl_view,
	jrnl_edit,
    
 	jrnl_delete,
    pub_other_view,
	
	pub_edit,
	pub_delete,
    
	
	jrnl_paper_edit,
	jrnl_paper_delete,
    
	resch_proj_view,
 	
    
 	resch_edit,
    resch_cons_edit,
  	resch_delete,
    resch_cons_delete,
   	#prj_outcm_view,
    
    prj_edit,
    prj_delete,
    
    resch_guide_view,
    
    resch_guide_edit,
    resch_guide_delete,
    
    fellow_award_view,
    
    fellow_award_edit,
    fellow_award_delete,
        
    
    lecture_paper_edit,
    lecture_paper_delete,
    
    
    lecture_elearn_edit,
    lecture_elearn_delete,
    
    api_summary_view,
    LetterView,
    LetterPDF,
    cas_sts_view,
    
)


app_name = 'catg_3'

urlpatterns = [

    
    path('<user_id>/letter/', LetterView, name="letter"),
    path('<user_id>/endo-view/', LetterPDF.as_view(), name="endo-view"),
    
	path('<user_id>/jrnl-pub/', jrnl_view, name="jrnl-pub"),
	path('jrnl-edit/<str:pk>/', jrnl_edit, name="jrnl-edit"),
 	path('jrnl-delete/<str:pk>/', jrnl_delete, name="jrnl-delete"),
 	
    path('<user_id>/pub-other/', pub_other_view, name="pub-other"),
    
	path('pub-edit/<str:pk>/', pub_edit, name="pub-edit"),
	path('pub-delete/<str:pk>/', pub_delete, name="pub-delete"),

	path('jrnl-paper-edit/<str:pk>/', jrnl_paper_edit, name="jrnl-paper-edit"),
	path('jrnl-paper-delete/<str:pk>/', jrnl_paper_delete, name="jrnl-paper-delete"),

 	path('<user_id>/resch-view', resch_proj_view, name="resch-view"),
	path('resch-edit/<str:pk>/', resch_edit, name="resch-edit"),
    path('resch-cons-edit/<str:pk>/', resch_cons_edit, name="resch-cons-edit"),
	path('resch-delete/<str:pk>/', resch_delete, name="resch-delete"),
    path('resch-cons-delete/<str:pk>/', resch_cons_delete, name="resch-cons-delete"),

	#path('<user_id>/prj-outcm-view', prj_outcm_view, name="prj-outcm-view"),
	
	path('prj-edit/<str:pk>/', prj_edit, name="prj-edit"),
 	path('prj-delete/<str:pk>/', prj_delete, name="prj-delete"),
    
    path('<user_id>/resch-guide-view', resch_guide_view, name="resch-guide-view"),
	path('resch-guide-edit/<str:pk>/', resch_guide_edit, name="resch-guide-edit"),
	path('resch-guide-delete/<str:pk>/', resch_guide_delete, name="resch-guide-delete"),

    
    path('<user_id>/fellow-award-view', fellow_award_view, name="fellow-award-view"),
	path('fellow-award-edit/<str:pk>/', fellow_award_edit, name="fellow-award-edit"),
	path('fellow-award-delete/<str:pk>/', fellow_award_delete, name="fellow-award-delete"),

   
	path('lecture-paper-edit/<str:pk>/', lecture_paper_edit, name="lecture-paper-edit"),
	path('lecture-paper-delete/<str:pk>/', lecture_paper_delete, name="lecture-paper-delete"),


	path('lecture-elearn-edit/<str:pk>/', lecture_elearn_edit, name="lecture-elearn-edit"),
	path('lecture-elearn-delete/<str:pk>/', lecture_elearn_delete, name="lecture-elearn-delete"),
    
    path('<user_id>/api-summary-view', api_summary_view, name="api-summary-view"),
    path('<user_id>/cas-sts-view', cas_sts_view, name="cas-sts-view"),    

     
    

]

notify/urls.py
from django.urls import path

from notify.views import (
	send_message,
    inbox,
    create_message,
    edit_message,
    view_message,
    delete_message,
 )
 
app_name = 'notify'


urlpatterns = [
	path('send/<int:receiver_id>/', send_message, name='send_message'),
    path('inbox/', inbox, name='inbox'),
    path('view/<int:message_id>/', view_message, name='view-message'),
    path('create/', create_message, name='create_message'),
    path('edit/<int:message_id>/', edit_message, name='edit-message'),
    path('delete/<int:message_id>/', delete_message, name='delete-message'),
]

notify/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime
from ckeditor.fields import RichTextField

# Create your models here.
class Message(models.Model):
    sender          = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_messages')
    receiver        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_messages')
    content         = RichTextField()
    timestamp       = models.DateTimeField(auto_now_add=True)
    read            = models.BooleanField(default=False)
    modified_date   = models.DateTimeField(auto_now=True)
    receiver_name   = models.TextField()
    email           = models.EmailField()
    feedback        = models.TextField()
   
    
    def __str__(self):
        return f"{self.sender} -> {self.receiver}: {self.content}"

notify/views.py
from django.shortcuts import render, get_object_or_404, redirect,reverse

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from notify.forms import MessageForm
#from django.contrib.auth.views import LoginView
from account.models import Account
#from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Message
from django.utils.html import strip_tags


@login_required
def send_message(request, receiver_id):
    if request.method == 'POST':
        content = request.POST.get('content')
        receiver = User.objects.get(id=receiver_id)
        message = Message.objects.create(sender=request.user, receiver=receiver, content=content)
        return redirect('notify:inbox')  # Replace 'inbox' with the name of your view displaying received messages
    else:
        receiver = User.objects.get(id=receiver_id)
        return render(request, 'notify/send_message.html', {'receiver': receiver})


def inbox(request,*args, **kwargs):
    #user_id = kwargs.get("user_id")
    user = request.user
    id_no = user.id
    #user_id = request.session['user_id']
    account = Account.objects.get(pk=user.id)
    
    print("l-34 ",user.id)
    received_messages = Message.objects.filter(receiver=user.id,read=False)
    sending_message = Message.objects.filter(sender=user.id) 
    
    if received_messages or sending_message or user.id == 1 : 
        return render(request, 'notify/inbox.html', {'messages': received_messages,'sending_message': sending_message,'account':account,'id_no':id_no})
    else:
        return redirect('account:home', user_id=id_no)
        
      
def create_message(request):
    
    if request.method == 'POST':
        form = MessageForm(request.POST)
        
        receiver = request.POST.get('receiver')
        
        account = Account.objects.get(pk=receiver)
        
        if form.is_valid():
            user = form.save(commit=False)
            user.receiver_name = account.username
            user.email = account.email
            
            user.save()
            return redirect('notify:inbox')
        
        
    form = MessageForm()     
    return render(request, 'notify/create_message.html', {'form': form})

def edit_message(request, message_id):
    message = Message.objects.get(pk=message_id)
    content_text=message.content
    #user_id = request.session['user_id']
    user = request.user
    id_no = user.id
    account = Account.objects.get(pk=user.id)
    hide_sender = False
    hide_receiver = False
    
    if not account.is_superuser: 
        hide_sender = True  # Set this to True or False based on your condition
        hide_receiver = True  # Set this to True or False based on your condition
        
        
    if request.method == 'POST':
        form = MessageForm(request.POST, instance=message)
        receiver = request.POST.get('receiver')        
        account = Account.objects.get(pk=receiver)
        
        if form.is_valid():
            user = form.save(commit=False)
            
            user.receiver_name = account.username
           
            if hide_sender and hide_receiver:
                user.read = True
                
                print('l-145',user.content)
            else:
                user.timestamp = user.modified_date
                user.read = False
            user.email = account.email
            user.save()
            
            return redirect('notify:inbox')
    else:
        form = MessageForm(instance=message)
    return render(request, 'notify/edit_message.html', {'form': form, 'message': message,'hide_sender': hide_sender, 'hide_receiver': hide_receiver,'content_text':content_text,'id_no':id_no})


def view_message(request,message_id):     
    
    message = get_object_or_404(Message, pk=message_id)
    
    if not message.read:        
        message.read = True       
        message.save()
       
    return redirect('dashboard')
    

def delete_message(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    message_subject = message.content  # Save the subject for displaying in the message

    message.delete()

    # Redirect to inbox after deletion
    return redirect('notify:inbox')

notify/templates/notify/create_message.html
<!-- create_message.html -->
{% extends 'base_admin.html' %}

{% load static %}

{% block content %}
<head>
  
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	
	<script>
		jQuery(document).ready(function($) {
			$("#myModal").modal('show');
			CKEDITOR.replace('id_content', {
				width: '100%', // Set the width to 100%
				// Other configuration options...
			}); 
		});
	</script>
	<style>
		.modal {
		   position: absolute;
		   top: 10%;
		   left: 10%;
		}
		.modal-dialog {
					max-width: 1200px; /* Adjust this value to your desired width */
		}
	</style>
</head>
<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog">
    
		  <!-- Modal content-->
		  <div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title">Create Message</h2>
			</div>
			<div class="modal-body">
				<form method="post">
					{% csrf_token %}
					From : {{ form.sender }} To : {{ form.receiver }}
					<br>
					<div style="width: 100%;">
						<textarea name="content" cols="40" rows="10" id="id_content"></textarea>
					</div>
    
					<br>
					<button type="submit" class="btn btn-info">Send Message</button>
				</form>
				<div class="modal-footer">				
					<button type="button"  class="btn btn-secondary" id="closeModalBtn" data-dismiss="modal">Close</button>
				</div>
			</div>	
		  </div>
		</div>
</div>
	<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
        <script>
          $(document).ready(function() {
            // Function to make 'feedback' field optional
            function makeFeedbackOptional() {
              $('textarea[name="feedback"]').prop('required', false);
			  $('textarea[name="feedback"]').val('');
			  $('textarea[name="feedback"]').hide();
			}

            // Call the function to make the field optional
            makeFeedbackOptional();
          });
		  
			var closeModalBtn = document.getElementById("closeModalBtn");

			// Add an event listener to the close button
			closeModalBtn.addEventListener("click", function() {
			  // Redirect to the previous page
			  //history.back();
			  
			  window.location.href = "{% url 'account:home' user_id=1 %}";
				
			});
			
			$('#myModal').modal({backdrop: 'static', keyboard: false});  
	
		</script>
		
{% endblock %}

notify/templates/notify/edit_message.html
{% extends 'base_admin.html' %}

{% block content %}
<head>
  
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	
	<script>
		jQuery(document).ready(function($) {
			$("#myModal").modal('show');
			CKEDITOR.replace('id_content', {
				width: '100%', // Set the width to 100%
				// Other configuration options...
			}); 
		});
	</script>
	<style>
		.modal {
		   position: absolute;
		   top: 2%;
		   left: 10%;
		}
		.modal-dialog {
					max-width: 1200px; /* Adjust this value to your desired width */
		}
	</style>
  </head>
	{% block error_messages %}
	{% endblock error_messages %}
	
	<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog">
    
		  <!-- Modal content-->
		  <div class="modal-content">
			<div class="modal-header">
			  <h2 class="modal-title">Reply</h2>
				
					
			  <form id="editForm" method="post">
				
				
			</div>
			<div class="modal-body">
				{% csrf_token %}
				
				{% if hide_sender %}
					{{ form.sender.as_hidden }}
					{{ form.receiver.as_hidden }}
					<div id="contentDiv" style="display:none;">
						{{ form.content }}
					</div>
					<textarea class="form-control" name="feedback" cols="20" rows="3" readonly required id="id_cont" style="color: blue;font-weight:bold;font-size:20px;"></textarea>
				
					
				{% else %}
					From : {{ form.sender }} To : {{ form.receiver }}
					<p></p>
					<p style="color:black;font-weight:bold;"><u>Message Content</u></p>
					
					{{ form.content }}
					
				
				{% endif %}
				
				<br>
				<br>
				<p style="color:black;font-weight:bold;"><u>Your Response</u></p>
				<textarea class="form-control" name="feedback" cols="20" rows="3" required id="id_feedback" style="color: black;">{{ form.feedback.value }}</textarea>
				
				<br>
				<button type="submit" class="btn-info" >Send</button>
			  </form>
				<div class="modal-footer">				
					<button type="button"  class="btn btn-secondary" id="closeModalBtn" data-dismiss="modal">Close</button>
				</div>
			</div>
		  </div>
		</div>
	</div>
  	<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>

  <script>
			$(document).ready(function() {
			  {% if hide_sender %}
				$('select[name="sender"]').hide();
				var value = $("#id_content").val();	
				var textWithoutTags = value.replace(/<[^>]*>/g, '');		
				$("#id_cont").val(textWithoutTags);
				$('label[for="{{ form.sender.id_for_label }}"]').hide();
				document.querySelector('textarea[name="content"]').readOnly = true;
				
			  {% else %}
				$("#id_sender option[value=1]").attr('selected', 'selected');
				function makeFeedbackOptional() {
					  $('textarea[name="feedback"]').prop('required', false);
					  $('textarea[name="feedback"]').val('');			  
					 
				}
				
				makeFeedbackOptional();
				
			  {% endif %}
			  
			});
			var closeModalBtn = document.getElementById("closeModalBtn");

			// Add an event listener to the close button
			closeModalBtn.addEventListener("click", function() {
			  // Redirect to the previous page
			  //history.back();
			  var id_no = {{ id_no }};
			  window.location.href = "{% url 'account:home' user_id=id_no %}";
				
			});
			
			$('#myModal').modal({backdrop: 'static', keyboard: false});  

  </script>
{% endblock %}

notify/templates/notify/inbox.html
{% extends 'base_admin.html' %}
{% block content %}

<head>
  
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
		
		<script>
			jQuery(document).ready(function($) {
				$("#myModal").modal('show');
			});
		</script>

		<style>
				/* static/your_app/styles.css */

				/* Style the message list */
				ul {
				  list-style: none;
				  padding: 0;
				  margin: 0;
				}

				/* Style each message item */
				li {
				  margin-bottom: 10px;
				  padding: 10px;
				  border: 1px solid #ccc;
				  border-radius: 5px;
				}

				/* Style the sender and receiver information */
				li span {
				  font-weight: bold;
				}

				/* Style the date */
				li small {
				  color: #999;
				}

				/* Optional: Center the inbox heading */
				h1 {
				  text-align: center;
				}
				.modal {
				   position: absolute;				   
				   top: 10%;
				   left: 10%;
				}
				.modal-dialog {
					max-width: 1200px; /* Adjust this value to your desired width */
				}
				
		</style>
</head>
{% block error_messages %}
{% endblock error_messages %}

	<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog">
    
		  <!-- Modal content-->
		  <div class="modal-content">
			<div class="modal-header">
	 
			 {% if account.is_superuser %}
				<h2 class="modal-title">Sent Messages</h2>
				
				<br>
				<p><a style="color:teal;font-size:20px;font-weight:bold;" href="{% url 'notify:create_message' %}">Compose New Message</a></p>
			 {% else %}
				<h1 class="inbox-heading">Admin Notification</h1>
			 {% endif %}
			</div>
			<div class="modal-body">
			  <ul class="message-list">
				{% for message in messages %}
				  <li class="message-item">
					<span class="message-sender">From :&nbsp&nbsp IQAC-Admin</span>
					<small class="message-date">{{ message.timestamp|date:"F d, Y" }}</small>
					<span  style="float:right;color:teal;"><a href="{% url 'notify:edit-message' message_id=message.id %}">Reply Here</a></span>
										
					<br>
					<p style="color: blue; font-family: Arial, sans-serif;">{{ message.content|safe }}</p>
					
					<br>
					<b>My Response :&nbsp&nbsp</b>
					<p>
						<span style="background-color: yellow;">{{ message.feedback }}</span>
					</p>
				  </li>
				{% endfor %}
				</ul>
				<ul>
				{% for message in sending_message %}
				
				  <li class="message-item">
				   
					<span class="message-sender">From :&nbsp&nbsp IQAC-Admin</span>
					<small class="message-date">{{ message.timestamp|date:"F d, Y" }}</small>
					&nbsp&nbsp<span class="message-sender">To :&nbsp&nbsp {{ message.receiver_name }} -->{{ message.email }}</span>
					
					<span style="float:right;"><a href="{% url 'notify:edit-message' message_id=message.id %}">Edit Message</a></span>
					<span style="float:right;margin-right:10px;color:black;"><a href="{% url 'notify:delete-message' message_id=message.id %}" class="message-delete-button">Delete</a></span>
					<br>
					<p style="color: blue; font-family: Arial, sans-serif;">{{ message.content|safe }}</p>
					
					<br>
					<b>Feedback :&nbsp&nbsp</b>
					{% if message.read %}
						&nbsp&nbsp<span class="message-sender" style="color:red;">Responded on : {{ message.modified_date|date:"F d, Y" }}</span>
					{% endif %}
					<p>
						<span style="background-color: yellow;">{{ message.feedback }}</span>
					</p>
				{% endfor %}
			  </ul>
				<div class="modal-footer">				
					<button type="button"  class="btn btn-secondary" id="closeModalBtn" data-dismiss="modal">Close</button>
				</div>
			</div>
		  </div>
	    </div>
	</div>
		
	
	<script>
			var closeModalBtn = document.getElementById("closeModalBtn");

			// Add an event listener to the close button
			closeModalBtn.addEventListener("click", function() {
			  // Redirect to the previous page
			  //history.back();
			  var id_no = {{ id_no }};
			  
			  window.location.href = "{% url 'account:home' user_id=id_no %}";
				
			});
			
			$('#myModal').modal({backdrop: 'static', keyboard: false})  

	</script>	
{% endblock %}

notify/templates/notify/send_message.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	{% for user in users %}
		<a href="{% url 'send_message' user.id %}">Send message to {{ user.username }}</a><br>
	{% endfor %}
  <h1>Send Message</h1>
  <form method="post">
    {% csrf_token %}
    <textarea name="content" rows="5" cols="50" required></textarea><br>
    <input type="submit" value="Send">
  </form>
{% endblock %}